### ISSUE TITLE
errors in build with matlab

### ISSUE THREAD

**Issue by shaoxh** [borglab/gtsam#894]
## Description

build ../wrap/gtsam/gtsam_wrapper.cpp failed!

## Steps to reproduce

1.  cmake -DGTSAM_INSTALL_MATLAB_TOOLBOX=ON  \
	   -DEXAMPLES_BUILD_MATLAB_TOOLBOX:OPTION=ON \
	   -DGTSAM_TOOLBOX_INSTALL_PATH:PATH=$HOME/toolbox  ..
2. make install

## Expected behavior
build successfully

## Environment

Matlab 2021
python 3.6.5
c++ 14
ubuntu 18.04

## Additional information
  [100%] Built target ConcurrentFilteringAndSmoothingExample
[100%] Generating ../wrap/gtsam/gtsam_wrapper.cpp
[MatlabWrapper] Ignoring classes: ['gtsam::Point2', 'gtsam::Point3', 'gtsam::CustomFactor']
Traceback (most recent call last):
  File "/home/godu/gtsam/wrap/scripts/matlab_wrap.py", line 58, in <module>
    cc_content = wrapper.wrap(sources, path=args.out)
  File "/home/godu/gtsam/wrap/gtwrap/matlab_wrapper/wrapper.py", line 1576, in wrap
    parsed_result = parser.Module.parseString(content)
  File "/home/godu/gtsam/wrap/gtwrap/interface_parser/module.py", line 56, in parseString
    return Module.rule.parseString(s)[0]
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3467, in parseImpl
    return e._parse( instring, loc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3858, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3467, in parseImpl
    return e._parse( instring, loc, doActions )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/home/godu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "/home/godu/gtsam/wrap/gtwrap/interface_parser/variable.py", line 42, in <lambda>
    t.default[0] if isinstance(t.default, ParseResults) else None))
  File "/home/godu/gtsam/wrap/gtwrap/interface_parser/variable.py", line 49, in __init__
    self.ctype = ctype[0]  # ParseResult is a list
TypeError: 'Type' object does not support indexing
matlab/CMakeFiles/gtsam_matlab_wrapper.dir/build.make:74: recipe for target 'wrap/gtsam/gtsam_wrapper.cpp' failed
make[2]: *** [wrap/gtsam/gtsam_wrapper.cpp] Error 1
CMakeFiles/Makefile2:36764: recipe for target 'matlab/CMakeFiles/gtsam_matlab_wrapper.dir/all' failed
make[1]: *** [matlab/CMakeFiles/gtsam_matlab_wrapper.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by varunagrawal** [comment]
Okay I'm looking into it.

**Comment by shaoxh** [comment]
> @varunagrawal I think the wrap update has broken MATLAB?
> 
> @shaoxh Please use a version before [d2bb299](https://github.com/borglab/gtsam/commit/d2bb29950725461bcf634156ffbe6fa9195700f6) and see if that works.

I used this commit but not work. Is there something wrong with the python version?

-- Building GTSAM - shared: ON
-- Found Python: /home/godu/anaconda3/bin/python3.6 (found suitable exact version "3.6.5") found components:  Interpreter Development 
-- gtwrap Package config : /usr/local/lib/cmake/gtwrap


godu@godu-Precision-7820-Tower:~/gtsam/build$ git log 
commit 108cd13ecd1cda7acbb62360628b526b8336ea80 (HEAD)
Merge: b4b2f41f2 4307b842c
Author: Varun Agrawal <varagrawal@gmail.com>
Date:   Tue Sep 28 10:09:10 2021 -0400

    Merging 'master' into 'wrap'

**Comment by varunagrawal** [comment]
And what is your OS version?

**Comment by shaoxh** [comment]
> And what is your OS version?

oh， it's ubuntu 18.04.
